plugins:
  - jekyll-paginate

title: Yo's Memo
description: “change - I had, however, already a different ideal, derived, I suppose, from mathematics."
paginate: 10
paginate_path: /page/:num/
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
