plugins:
  - jekyll-paginate

title: Yo's Memo
description: Good morning. Good afternoon. Goor evening. Good night. 
paginate: 10
paginate_path: /page/:num/
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
