plugins:
  - jekyll-paginate

title: Integration by me
description: Then you will know the truth, and the truth will set you free.
paginate: 10
paginate_path: /page/:num/
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: jdh8
